// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkk-5CyrlI3rmGK7ETpCHd0Yi624FYEY4',
    appId: '1:180685581885:web:32ea7e77d6d42c871f0454',
    messagingSenderId: '180685581885',
    projectId: 'homespot-44d66',
    authDomain: 'homespot-44d66.firebaseapp.com',
    storageBucket: 'homespot-44d66.appspot.com',
    measurementId: 'G-3YW2NZC1H4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEK7mO7nODd8tym5HnDnWqlwvW0UTFhOg',
    appId: '1:180685581885:android:5bed6be39ae7525f1f0454',
    messagingSenderId: '180685581885',
    projectId: 'homespot-44d66',
    storageBucket: 'homespot-44d66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhkRibx88BNiClW3ZBR3ixrfEDPrvW04k',
    appId: '1:180685581885:ios:042ea541b55c5e1b1f0454',
    messagingSenderId: '180685581885',
    projectId: 'homespot-44d66',
    storageBucket: 'homespot-44d66.appspot.com',
    iosBundleId: 'com.example.workersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhkRibx88BNiClW3ZBR3ixrfEDPrvW04k',
    appId: '1:180685581885:ios:042ea541b55c5e1b1f0454',
    messagingSenderId: '180685581885',
    projectId: 'homespot-44d66',
    storageBucket: 'homespot-44d66.appspot.com',
    iosBundleId: 'com.example.workersApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkk-5CyrlI3rmGK7ETpCHd0Yi624FYEY4',
    appId: '1:180685581885:web:559fedaaf1c4de121f0454',
    messagingSenderId: '180685581885',
    projectId: 'homespot-44d66',
    authDomain: 'homespot-44d66.firebaseapp.com',
    storageBucket: 'homespot-44d66.appspot.com',
    measurementId: 'G-3BQPGRYV0N',
  );
}
